project:
  type: website

website:
  title: "ISSS626-GAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1"
            href: "Hands-on_exercise/Hands-on_ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_exercise/Hands-on_ex02/Hands-on_Ex02.html"  # Example additional link
      - text: "In-class Exercise"  # New menu for In-class exercises
        menu:
          - text: "In-class Exercise 1"
            href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
          - text: "In-class Exercise 2"
            href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"  # Example additional link
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmos
    css: styles.css
    toc: true

editor: visual